### ISSUE TITLE
CONFIGURATION_NOT_FOUND

### ISSUE THREAD

**Issue by AmirNaghibi** [Th3Wall/Fakeflix#14]
I have followed instructions to set up **.env** file. However, I get **CONFIGURATION_NOT_FOUND**. Any idea how to resolve this? 

seems like it doesn't like my **REACT_APP_FIREBASE_API_KEY**

Cool project btw. I'm really looking forward to exploring it more 😃  

<img width="1213" alt="Screen Shot 2021-07-06 at 11 45 31 PM" src="https://user-images.githubusercontent.com/20001191/124712586-5b2baa80-deb4-11eb-8790-8042b2a4caba.png">

**Comment by AmirNaghibi** [comment]
NVM it is working 🎉 ! I had to enable **enabled the Sign-in method under Authentication in firebase console.**
src: https://stackoverflow.com/questions/66702421/firebase-code-400-message-configuration-not-found


I also faced an issue of **Failed to get document because the client is offline.** due to not having set up a firestore database on firebase.

**Comment by Th3Wall** [comment]
Hi @AmirNaghibi!
Glad to see you fixed the config problems you had. Hope you will like the whole project 😄

I'm closing this issue
Davide
