### ISSUE TITLE
Suggestion: Use Backblaze

### ISSUE THREAD

**Issue by Lexxos** [Th3Wall/Fakeflix#19]
Use backblaze B2 for video downloading. I used it on a social media website and the photo and videos appear instantly. It beat out Amazon S3 by 95ms. In terms of response, Backblaze was at about 5ms. 

$0.005 Storage

Service | AWS S3 | Backblaze B2 | AWS Markup
------------ | ------------- | ------------- | -------------
Storage (GB) | $0.023 | $0.005 | 360%
Download (GB) | $0.09 | $0.01 | 800%
Redundancy (GB) | $0.023 per location | FREE across 9-14 locations | N/A
Requests | $0.0004 / 1000 | $0.004 / 10000 | 0%

Of course if this uses S3, it has compatible APIs so it's very easy for anyone to switch out.

**Comment by Th3Wall** [comment]
Thank you for the advice @Lexxos, I will consider it if I'll add also videos to the platform. At the moment I only have images and info data to display.
Cheers.
