### ISSUE TITLE
Will you have a course or video on how you created it?

### ISSUE THREAD

**Issue by LuisMartinez1** [Th3Wall/Fakeflix#20]
Hi, I would like to know if there is a course or video on how you created it since I am new in react and there are many things that I cannot understand. I hope you can help me, I thank you very much. Greetings.

**Comment by Th3Wall** [comment]
Hi @LuisMartinez1,

I currently don't have a course video on how I have created Fakeflix, but the best advice I might give you is that this one might not be the best project to start practicing.
I've started with some very little and easy projects before choosing to develop Fakeflix, you should do that too.

Maybe you can have a look at my other React projects on my profile (calculator, [pomododro timer](https://github.com/Th3Wall/react-pomodoro-clock), [quote generator](https://github.com/Th3Wall/react-quote-generator), a [drum machine](https://github.com/Th3Wall/react-drum-machine) and a little [ecom](https://github.com/Th3Wall/react-crwn-cothing-ecom)) and try to understand and recreate them.

Good luck!
Th3Wall
