### ISSUE TITLE
TV Series

### ISSUE THREAD

**Issue by fossdd** [Th3Wall/Fakeflix#22]
Currently Fakeflix only supports Movies with one video, even if the item is a series of videos like Stranger Things.

It would nice to support them too. At best with the solution Netflix did.

**Comment by Th3Wall** [comment]
Hi @fossdd, thank you for your suggestion.
During the development phase I evaluated whether to include also this feature but in the end I decided not to include it.
It might be a nice upgrade for the future, who knows...👀

Thanks.
Davide
