### ISSUE TITLE
The video in README.md isn't is a link instead of a video embed

### ISSUE THREAD

**Issue by Tresquel** [Th3Wall/Fakeflix#25]
![Screenshot_2021-11-23-16-52-05-46_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/43729305/143057625-eb1dc72a-1de7-4db2-9dea-2173eeece92e.jpg)

**Comment by Th3Wall** [comment]
Hi! It depends from where you open the README.
If you open it from your laptop you'll see it correctly, if you open it from your mobile app you'll see the link (that still works but obviously in another page) 😄
