### ISSUE TITLE
Friendly note, your API keys are exposed.

### ISSUE THREAD

**Issue by AyushSl** [Th3Wall/Fakeflix#27]
From the React docs

> WARNING: Do not store any secrets (such as private API keys) in your React app!
> 
> Environment variables are embedded into the build, meaning anyone can view them by inspecting your app's files.

(Source: https://create-react-app.dev/docs/adding-custom-environment-variables/)

Also, your API keys are currently visible in the Network tab of the browser DevTools.

Great work, by the way.

**Comment by Th3Wall** [comment]
Hi @AyushSl, thank you for the friendly reminder. I'm aware of it :)
