### ISSUE TITLE
Friendly tip, don't upload your .env file to a public repo. Now your api keys and everything are exposed. 

### ISSUE THREAD

**Issue by Steveiwonder** [Th3Wall/Fakeflix#3]
Delete it, add it to git ignore and also go and revoke all those keys.

**Comment by Th3Wall** [comment]
Thanks, I've fixed it :)

**Comment by wrejcodes** [comment]
These files are still available through the git history by the way. 

https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository

**Comment by Steveiwonder** [comment]
> Thanks, I've fixed it :)

No worries, nice project BTW
