### ISSUE TITLE
Netifly deployment not working

### ISSUE THREAD

**Issue by ajeje93** [Th3Wall/Fakeflix#33]
The deployment is marked as malicious by Google Chrome and clicking proceed opens a page saying "Not found".

![Screenshot_2022-03-30-21-31-19-647_com android chrome](https://user-images.githubusercontent.com/11637841/160915961-01629fe7-91d1-462e-bac5-c02225790ab2.jpg)
![Screenshot_2022-03-30-21-31-23-241_com android chrome](https://user-images.githubusercontent.com/11637841/160915981-271f2bf7-f5a4-4227-bb2f-f3cf7ec64c72.jpg)

**Comment by Th3Wall** [comment]
Hey @ajeje93, 
I accidentally forgot to remove the Netlify link from the README after moving the deployment to a custom domain.
Thanks a lot for spotting it! :)

Th3Wall
