### ISSUE TITLE
Video playback

### ISSUE THREAD

**Issue by DomiiBunn** [Th3Wall/Fakeflix#4]
I'm wondering why not implement video playback? I can imagine it being cool for home theater use ^.^

**Comment by sh4d0wph03n1x** [comment]
Having actual playback would require the creator to pay for the movies and the rights to use them. If they didn't, it would be piracy, and the project would be as fucked as a toddler on Epstein's island when Biden comes around.

**Comment by DomiiBunn** [comment]
> Having actual playback would require the creator to pay for the movies and the rights to use them. If they didn't, it would be piracy, which is illegal.

Depends. Let's say someone has a lot of old DVDs and wants to host a local media server, rn they basically have 2 options plex or diy that's hard to use...thus host something like this locally and bons your uncle. Would be cool if it hooked up with the movie database API to get description and splash from just the title

**Comment by fossdd** [comment]
Yes, actually that was also my question. Something like that would wonderfull. Then you could have a folder with films mapped with the TMDB's IDs. (JSON?). Then if you play the film it plays the file and if the mapped entry doesn't exist, say a short text after the fakeflix intro.

This project then will have a use, instead only for testing.

**Comment by DomiiBunn** [comment]
I could try to help a bit with the backend if needed, tho i might be lacking some skills

**Comment by fossdd** [comment]
Could also done in the front end getting the json and the videos from the server would not "so" difficult, but I don't know much about the code and JavaScript.

**Comment by Shetty073** [comment]
I might do something like this in the near future using this as frontend. Maybe use laravel or express for backend 🤔.

**Comment by DomiiBunn** [comment]
@Th3Wall fell free to close this if it's not the idea behind the project @Shetty073 I'd be happy to help in express if i find time. Lmk and we'll hook up

**Comment by Shetty073** [comment]
Okay great.. looking forward to collaborate with you @DomiiBunn

**Comment by DomiiBunn** [comment]
Discord: ✮✯⋆DomiiBunn⋆✯✮#0898

**Comment by enovision** [comment]
Maybe use the trailers mentioned in the TMDB API results? They all lead to Youtube links and are publicly viewable.

**Comment by Th3Wall** [comment]
@DomiiBunn thank you for your suggestion. Anyway, my initial idea was to build just the front end, maybe in the future I might upgrade it, but it's not planned atm since I have a lot of projects in mind.

@enovision thank you too. I know that I can also pull YT and Vimeo trailers from the TMDB API results.
I might insert them soon 😄 .
