### ISSUE TITLE
noob here 

### ISSUE THREAD

**Issue by mikkipopup** [Th3Wall/Fakeflix#8]
sorry but i m a noob in such projects ,,,i am interested in ur project and want to run fakeflix on my pc.plz tell me how can i create .env file and adding api key into it and rest of the process in steep by step guide.i shall be very thankful to u..waiting for ur reply.

**Comment by sitemapxml** [comment]
Hi,
you just need to copy .env.sample to .env and fill the info...
For the TMDB api key, you can check the [docs](https://developers.themoviedb.org/3/getting-started/introduction)
Good luck!
Regards,

**Comment by Th3Wall** [comment]
> Hi,
> 
> you just need to copy .env.sample to .env and fill the info...
> 
> For the TMDB api key, you can check the [docs](https://developers.themoviedb.org/3/getting-started/introduction)
> 
> Good luck!
> 
> Regards

Yeah, basically all you need to do is to copy the .env.sample file to a .env file and fill it with the TMDB API key (that you can get from their website) and with the Firebase configuration that you will have once created a project inside Firebase.

Let me know if I can be more helpful.
